#!/usr/bin/env bash

source ./.env

DEFAULT_NGINX_CONFIG=./default-moodle-nginx.conf
NGINX_CONFIG=./my-moodle-nginx.conf


if test -f "$DEFAULT_NGINX_CONFIG"; then

    sed "s/MOODLE_DOMAIN/$MOODLE_DOMAIN/g"   $DEFAULT_NGINX_CONFIG > $NGINX_CONFIG
    sed -i "s/MOODLE_NETWORK/$MOODLE_NETWORK/g" $NGINX_CONFIG
    sed -i "s/MOODLE_PORT/$MOODLE_PORT/g"      $NGINX_CONFIG 
    
fi

rm -rf docker-compose.yml
cp docker-compose.yml.http docker-compose.yml
